/* Gerado a partir do catálogo "Descrição de máquinas da indústria da construção civil" (28/07/2025). */
window.CATALOGO_SEED = [
 {
  "id": "mec-70",
  "title": "MEC-70",
  "familia": "construcao-civil",
  "tipo": "Endireitadeira de arames",
  "selo": "",
  "excerpt": "Endireitadeira automática de arames CA 60, de 3,40 a 6,35 mm.",
  "description": "Endireitadeira automática com alimentação por rolos ou bobinas, endireitamento rotativo com castanha e corte mecânico por cisalhamento. Indicada para arames CA 60 de 3,40 a 6,35 mm.",
  "specs": "Função: Endireitadeira automática de arames\nAlimentação: Automática através de rolos ou bobinas\nBitolas de endireitamento: 3,40 a 6,35 mm\nMaterial: CA 60\nEndireitamento: Através de endireitador rotativo com castanha\nComprimento de corte: Mín. 100 mm, máx. 6.000 mm ou 12.000 mm\nCorte: Mecânico por cisalhamento\nForça motriz: Dois motores totalizando 6 H.P. + redutor\nProdução: Variável de 20 a 30 m.p.m. (em cortes longos)",
  "imageUrl": "img/maquinas/mec-70.webp",
  "status": "publicado"
 },
 {
  "id": "mec-90-c",
  "title": "MEC-90 C",
  "familia": "construcao-civil",
  "tipo": "Endireitadeira de arames",
  "selo": "",
  "excerpt": "Endireitadeira automática para CA 50 e CA 60, com endireitador rotativo de castanha.",
  "description": "Endireitadeira automática com alimentação por rolos ou bobinas, endireitamento rotativo com castanha e corte mecânico por cisalhamento, para CA 50 e CA 60 na construção civil.",
  "specs": "Função: Endireitadeira automática de arames\nAlimentação: Automática através de rolos ou bobinas\nMaterial a ser cortado: CA 50 e CA 60\nBitolas de endireitamento CA 50: ¼ a 5/16\"\nBitolas de endireitamento CA 60: 4,20 a 9,50 mm\nEndireitamento: Através de endireitador rotativo com castanha\nComprimento de corte: Mín. 500 mm, máx. 12.000 mm (para construção civil)\nCorte: Mecânico por cisalhamento\nForça motriz: Dois motores totalizando 11,5 H.P. + 1 redutor\nProdução: Variável de 20 a 30 m.p.m. (em cortes longos)",
  "imageUrl": "img/maquinas/mec-90-c.webp",
  "status": "publicado"
 },
 {
  "id": "mec-90-r",
  "title": "MEC-90 R",
  "familia": "construcao-civil",
  "tipo": "Endireitadeira de arames",
  "selo": "",
  "excerpt": "Endireitadeira automática com roletes parabólicos, CA 50 até 10 mm.",
  "description": "Endireitadeira automática com alimentação por rolos ou bobinas, endireitamento rotativo com roletes parabólicos e corte mecânico por cisalhamento, para CA 50 e CA 60.",
  "specs": "Função: Endireitadeira automática\nAlimentação: Automática através de rolos ou bobinas\nMaterial a ser cortado: CA 50 e CA 60\nBitolas de endireitamento CA 50: ¼ a 10 mm\nBitolas de endireitamento CA 60: 4,20 a 10 mm\nEndireitamento: Através de endireitador rotativo com roletes parabólicos\nComprimento de corte: Mín. 500 mm, máx. 12.000 mm (para construção civil)\nCorte: Mecânico por cisalhamento\nForça motriz: Dois motores totalizando 14,00 H.P. + redutor\nProdução: Variável de 15 a 20 m.p.m. (em cortes longos)",
  "imageUrl": "img/maquinas/mec-90-r.webp",
  "status": "publicado"
 },
 {
  "id": "mec-90-f",
  "title": "MEC-90 F",
  "familia": "construcao-civil",
  "tipo": "Endireitadeira de arames",
  "selo": "",
  "excerpt": "Endireitadeira automática com fieiras de vídea para CA 50 e CA 60.",
  "description": "Endireitadeira automática com alimentação por rolos ou bobinas, endireitamento rotativo com fieiras de vídea e corte mecânico por cisalhamento, para CA 50 e CA 60.",
  "specs": "Função: Endireitadeira automática de arames\nAlimentação: Automática através de rolos ou bobinas\nMaterial a ser cortado: CA 50 e CA 60\nBitolas de endireitamento CA 50: ¼ a 5/16\"\nBitolas de endireitamento CA 60: 4,20 a 9,50 mm\nEndireitamento: Através de endireitador rotativo com fieiras de vídea\nComprimento de corte: Mín. 500 mm, máx. 12.000 mm (para construção civil)\nCorte: Mecânico por cisalhamento\nForça motriz: Dois motores totalizando 16,50 H.P. + 1 redutor\nProdução: Variável de 20 a 30 m.p.m. (em cortes longos)",
  "imageUrl": "img/maquinas/mec-90-f.webp",
  "status": "publicado"
 },
 {
  "id": "mec-100-r",
  "title": "MEC-100 R",
  "familia": "construcao-civil",
  "tipo": "Endireitadeira de arames",
  "selo": "",
  "excerpt": "Endireitadeira automática para bitolas maiores, CA 50 de 6,35 a 12,70 mm.",
  "description": "Endireitadeira automática com alimentação por rolos ou bobinas, endireitamento por roletes em VND rolamentado e corte mecânico por cisalhamento, para CA 50 e CA 60.",
  "specs": "Função: Endireitadeira automática\nAlimentação: Automática através de rolos ou bobinas\nMaterial a ser cortado: CA 50 e CA 60\nBitolas de endireitamento CA 50: 6,35 a 12,70 mm\nBitolas de endireitamento CA 60: 6,00 a 9,50 mm\nEndireitamento: Através de roletes em VND rolamentado\nComprimento de corte: Mín. 100 mm, máx. 12.000 mm (para construção civil)\nCorte: Mecânico por cisalhamento\nForça motriz: Dois motores totalizando 16,5 H.P.\nProdução: Variável de 14 a 18 m.p.m. (em cortes longos)",
  "imageUrl": "img/maquinas/mec-100-r.webp",
  "status": "publicado"
 },
 {
  "id": "mec-170-su",
  "title": "MEC-170 SU",
  "familia": "construcao-civil",
  "tipo": "Máquina para fabricar estribos",
  "selo": "",
  "excerpt": "Dobradeira de estribos servo unidirecional, de 3,40 a 6,35 mm.",
  "description": "Máquina para dobra de estribos em diversos formatos, com três servo motores, dois pré-endireitadores e corte por cisalhamento acionado por servo motor. Versão unidirecional.",
  "specs": "Modelo: MEC-170 SU (servo unidirecional)\nFunção: Dobra de estribos em diversos formatos, unidirecional\nAlimentação: Automática através de rolos ou bobinas\nAcionamento: Três servo motores\nBitolas de dobra: 3,40 a 6,35 mm (em arames 3,4 e 4,2 trabalha com 2 fios)\nMaterial: CA 60\nÂngulo de dobra: De 0º a 180º\nDobra: Um cabeçote de dobra com acionamento por servo motor\nEndireitamento: Através de dois pré-endireitadores\nCorte: Por cisalhamento, acionado por servo motor\nForça motriz: Três servo motores com 3,0 N.m\nProdução: Variável entre 0 e 60 metros por minuto",
  "imageUrl": "img/maquinas/mec-170.webp",
  "status": "publicado"
 },
 {
  "id": "mec-170-sb",
  "title": "MEC-170 SB",
  "familia": "construcao-civil",
  "tipo": "Máquina para fabricar estribos",
  "selo": "",
  "excerpt": "Dobradeira de estribos servo bidirecional, de 3,40 a 6,35 mm.",
  "description": "Máquina para dobra de estribos em diversos formatos, com três servo motores, dois pré-endireitadores e corte por cisalhamento acionado por servo motor. Versão bidirecional.",
  "specs": "Modelo: MEC-170 SB (servo bidirecional)\nFunção: Dobra de estribos em diversos formatos, bidirecional\nAlimentação: Automática através de rolos ou bobinas\nAcionamento: Três servo motores\nBitolas de dobra: 3,40 a 6,35 mm (em arames 3,4 e 4,2 trabalha com 2 fios)\nMaterial: CA 60\nÂngulo de dobra: De 0º a 180º\nCabeçotes de dobra: Um cabeçote com acionamento por servo motor\nEndireitamento: Através de dois pré-endireitadores\nCorte: Por cisalhamento, acionado por servo motor\nForça motriz: Três servo motores com 3,5 N.m\nProdução: Variável entre 0 e 60 metros por minuto",
  "imageUrl": "img/maquinas/mec-170.webp",
  "status": "publicado"
 },
 {
  "id": "mec-180-h",
  "title": "MEC-180 H",
  "familia": "construcao-civil",
  "tipo": "Máquina para fabricar estribos",
  "selo": "",
  "excerpt": "Dobradeira de estribos bidirecional, de 3,40 a 8,00 mm em CA 60.",
  "description": "Máquina para dobra de estribos bidirecional, com servo motores, unidade hidráulica e pneumática, cabeçote de dobra hidráulico e dois pré-endireitadores.",
  "specs": "Função: Dobra de estribos em diversos formatos, bidirecional\nAlimentação: Automática através de rolos ou bobinas\nAcionamento: Servo motores, unidade hidráulica e pneumática\nComando: SEW\nBitolas de dobra e material: 3,40 a 8,00 mm em CA 60\nÂngulo de dobra: De 0º a 180º, acionado por servo motor\nCabeçotes de dobra: Um cabeçote com acionamento hidráulico\nEndireitamento e corte: Com dois pré-endireitadores\nCorte: Automático por cisalhamento, acionado por servo motor\nForça motriz: Dois servo motores com 5 N.m + motor de 3 HP\nProdução: Variável entre 0 e 40 metros por minuto",
  "imageUrl": "img/maquinas/mec-180-h.webp",
  "status": "publicado"
 },
 {
  "id": "kpp-d25",
  "title": "KPP D25",
  "familia": "construcao-civil",
  "tipo": "Dobradeira de vergalhão",
  "selo": "",
  "excerpt": "Dobradeira elétrica de vergalhões de até 1\" (25 mm).",
  "description": "Dobradeira de vergalhões com acionamento elétrico por motor de 3 HP + redutor e um cabeçote de dobra elétrico. Alimentação manual por barras retas previamente cortadas.",
  "specs": "Função: Dobras em vergalhões de até 1\"\nAlimentação: Manual através de barras retas previamente cortadas\nAcionamento: Elétrico com motor de 3 HP + redutor\nBitolas de dobra: 3,40 a 25,00 mm\nMaterial: CA 60 e CA 50\nÂngulo de dobra: De 40º a 180º\nCabeçotes de dobra: Um cabeçote com acionamento elétrico",
  "imageUrl": "img/maquinas/kpp-d25.webp",
  "status": "publicado"
 },
 {
  "id": "kpp-d32",
  "title": "KPP D32",
  "familia": "construcao-civil",
  "tipo": "Dobradeira de vergalhão",
  "selo": "",
  "excerpt": "Dobradeira elétrica de vergalhões de até 32 mm.",
  "description": "Dobradeira de vergalhões com acionamento elétrico por motor de 4 HP + redutor e um cabeçote de dobra elétrico. Alimentação manual por barras retas previamente cortadas.",
  "specs": "Função: Dobras em vergalhões de até 32 mm\nAlimentação: Manual através de barras retas previamente cortadas\nAcionamento: Elétrico com motor de 4 HP + redutor\nBitolas de dobra: 3,40 a 32,00 mm\nMaterial: CA 60 e CA 50\nÂngulo de dobra: De 40º a 180º\nCabeçotes de dobra: Um cabeçote com acionamento elétrico",
  "imageUrl": "img/maquinas/kpp-d32.webp",
  "status": "publicado"
 },
 {
  "id": "kpp-d38",
  "title": "KPP D38",
  "familia": "construcao-civil",
  "tipo": "Dobradeira de vergalhão",
  "selo": "",
  "excerpt": "Dobradeira elétrica de vergalhões de até 38 mm.",
  "description": "Dobradeira de vergalhões com acionamento elétrico por motor de 5 HP + redutor e um cabeçote de dobra elétrico. Alimentação manual por barras retas previamente cortadas.",
  "specs": "Função: Dobras em vergalhões de até 38 mm\nAlimentação: Manual através de barras retas previamente cortadas\nAcionamento: Elétrico com motor de 5 HP + redutor\nBitolas de dobra: 3,40 a 32,00 mm\nMaterial: CA 60 e CA 50\nÂngulo de dobra: De 40º a 180º\nCabeçotes de dobra: Um cabeçote com acionamento elétrico",
  "imageUrl": "img/maquinas/kpp-d38.webp",
  "status": "publicado"
 },
 {
  "id": "kpp-es16",
  "title": "KPP ES16",
  "familia": "construcao-civil",
  "tipo": "Dobradeira de vergalhão",
  "selo": "",
  "excerpt": "Dobradeira hidráulica de vergalhões de até 16 mm.",
  "description": "Dobradeira de vergalhões com acionamento hidráulico por motor de 3 HP e um cabeçote de dobra hidráulico. Alimentação manual por barras retas previamente cortadas.",
  "specs": "Função: Dobras em vergalhões de até 16 mm\nAlimentação: Manual através de barras retas previamente cortadas\nAcionamento: Hidráulico com motor de 3 HP\nBitolas de dobra: 3,40 a 16,00 mm\nMaterial: CA 60 e CA 50\nÂngulo de dobra: De 40º a 180º\nCabeçotes de dobra: Um cabeçote com acionamento hidráulico",
  "imageUrl": "img/maquinas/kpp-es16.webp",
  "status": "publicado"
 },
 {
  "id": "mec-c25",
  "title": "MEC-C25",
  "familia": "construcao-civil",
  "tipo": "Cortadeira de vergalhão",
  "selo": "",
  "excerpt": "Cortadeira elétrica de vergalhões de até 25 mm.",
  "description": "Cortadeira de vergalhões com acionamento elétrico por motor de 4 CV. Alimentação manual por barras retas previamente cortadas.",
  "specs": "Função: Corte em vergalhões de até 25 mm\nAlimentação: Manual através de barras retas previamente cortadas\nAcionamento: Elétrico com motor de 4 CV\nBitolas de corte: 3,40 a 25,00 mm\nMaterial: CA 60 e CA 50",
  "imageUrl": "img/maquinas/mec-c25.webp",
  "status": "publicado"
 },
 {
  "id": "mec-c38",
  "title": "MEC-C38",
  "familia": "construcao-civil",
  "tipo": "Cortadeira de vergalhão",
  "selo": "",
  "excerpt": "Cortadeira elétrica de vergalhões de até 38 mm.",
  "description": "Cortadeira de vergalhões com acionamento elétrico por motor de 4 CV. Alimentação manual por barras retas previamente cortadas.",
  "specs": "Função: Corte em vergalhões de até 38 mm\nAlimentação: Manual através de barras retas previamente cortadas\nAcionamento: Elétrico com motor de 4 CV\nBitolas de corte: 3,40 a 38,00 mm\nMaterial: CA 60 e CA 50",
  "imageUrl": "img/maquinas/mec-c38.webp",
  "status": "publicado"
 },
 {
  "id": "mec-kl",
  "title": "MEC-KL",
  "familia": "construcao-civil",
  "tipo": "Máquina para rolos de arame recozido",
  "selo": "",
  "excerpt": "Faz rolos de arame recozido, 2 rolos de 1 kg a cada 30 a 40 segundos.",
  "description": "Máquina para fazer rolos de arame recozido, com alimentação automática por rolos ou bobinas e acionamento elétrico por motor de 3 HP + redutor.",
  "specs": "Função: Fazer rolos de arame recozido\nProdução: 2 rolos de 1 kg a cada 30 a 40 segundos\nAlimentação: Automática através de rolos ou bobinas\nBitolas de trabalho: Arames 18 e 16\nMaterial: Arame recozido\nAcionamento: Elétrico com motor de 3 HP + redutor",
  "imageUrl": "img/maquinas/mec-kl.webp",
  "status": "publicado"
 },
 {
  "id": "mec-kl-torcido",
  "title": "MEC-KL (2 fios torcidos)",
  "familia": "construcao-civil",
  "tipo": "Máquina para rolos de arame recozido",
  "selo": "",
  "excerpt": "Faz rolos de arame recozido torcidos com 2 fios.",
  "description": "Versão da MEC-KL para rolos de arame recozido torcidos com 2 fios, com alimentação automática por rolos ou bobinas e acionamento elétrico por motor de 3 HP + redutor.",
  "specs": "Função: Fazer rolos de arame recozido torcidos com 2 fios\nProdução: 2 rolos de 1 kg a cada 30 a 40 segundos\nAlimentação: Automática através de rolos ou bobinas\nBitolas de trabalho: Arames 18 e 16\nMaterial: Arame recozido\nAcionamento: Elétrico com motor de 3 HP + redutor",
  "imageUrl": "img/maquinas/mec-kl-torcido.webp",
  "status": "publicado"
 },
 {
  "id": "mec-140-lajes-10hp",
  "title": "MEC-140 LAJES (10 HP)",
  "familia": "construcao-civil",
  "tipo": "Endireitadeira e dobradeira para lajes",
  "selo": "",
  "excerpt": "Endireitadeira com dobras nas pontas para lajes, arames de 5,00 a 10,00 mm.",
  "description": "Endireitadeira de arames com dobras nas pontas, para lajes. Versão de 10 HP para arames de 5,00 a 10,00 mm.",
  "specs": "Função: Endireitadeira de arames com dobras nas pontas\nAlimentação: Automática através de rolos ou bobinas\nProdução: 10 a 15 m/min em cortes longos\nAcionamento: Elétrico e pneumático\nForça motriz: 10 HP + redutor\nEndireitamento: Através de endireitador rotativo com castanhas ou vídeas\nComprimento de corte: Mín. 500 mm, máx. 12.000 mm (para construção civil)\nCorte: Mecânico por cisalhamento\nBitolas de trabalho: Arames 5,00 mm a 10,00 mm\nMaterial: CA 50 e CA 60",
  "imageUrl": "img/maquinas/mec-140-lajes.webp",
  "status": "publicado"
 },
 {
  "id": "mec-140-lajes-75hp",
  "title": "MEC-140 LAJES (7,5 HP)",
  "familia": "construcao-civil",
  "tipo": "Endireitadeira e dobradeira para lajes",
  "selo": "",
  "excerpt": "Endireitadeira com dobras nas pontas para lajes, arames de 3,40 a 8,00 mm.",
  "description": "Endireitadeira de arames com dobras nas pontas, para lajes. Versão de 7,5 HP para arames de 3,40 a 8,00 mm.",
  "specs": "Função: Endireitadeira de arames com dobras nas pontas\nAlimentação: Automática através de rolos ou bobinas\nProdução: 10 a 15 m/min em cortes longos\nAcionamento: Elétrico e pneumático\nForça motriz: 7,5 HP + redutor\nEndireitamento: Através de endireitador rotativo com castanhas ou vídeas\nComprimento de corte: Mín. 500 mm, máx. 12.000 mm (para construção civil)\nCorte: Mecânico por cisalhamento\nBitolas de trabalho: Arames 3,40 mm a 8,00 mm\nMaterial: CA 50 e CA 60",
  "imageUrl": "img/maquinas/mec-140-lajes.webp",
  "status": "publicado"
 },
 {
  "id": "desbobinador-300",
  "title": "Desbobinador rotativo 300 kg",
  "familia": "construcao-civil",
  "tipo": "Desbobinador",
  "selo": "",
  "excerpt": "Desbobinador comum rotativo para rolos de até 300 kg.",
  "description": "Desbobinador comum rotativo para rolos de até 300 kg.",
  "specs": "Tipo: Desbobinador comum rotativo\nCapacidade: Rolos de até 300 kg",
  "imageUrl": "img/maquinas/desbobinador-300.webp",
  "status": "publicado"
 },
 {
  "id": "desbobinador-1000",
  "title": "Desbobinador porta spyder 1.000 kg",
  "familia": "construcao-civil",
  "tipo": "Desbobinador",
  "selo": "",
  "excerpt": "Desbobinador rotativo tipo porta spyder para rolos de até 1.000 kg.",
  "description": "Desbobinador rotativo do tipo porta spyder para rolos de até 1.000 kg.",
  "specs": "Tipo: Desbobinador rotativo porta spyder\nCapacidade: Rolos de até 1.000 kg",
  "imageUrl": "img/maquinas/desbobinador-1000.webp",
  "status": "publicado"
 },
 {
  "id": "desbobinador-2000",
  "title": "Desbobinador rotativo 2.000 kg",
  "familia": "construcao-civil",
  "tipo": "Desbobinador",
  "selo": "",
  "excerpt": "Desbobinador rotativo para bobinas de até 2.000 kg.",
  "description": "Desbobinador rotativo para bobinas de até 2.000 kg.",
  "specs": "Tipo: Desbobinador rotativo\nCapacidade: Bobinas de até 2.000 kg",
  "imageUrl": "img/maquinas/desbobinador-2000.webp",
  "status": "publicado"
 }
];
